### ISSUE TITLE
Xcode 15

### ISSUE THREAD

**Issue by gitMartynas** [RxSwiftCommunity/RxSwiftExt#272] opened 2023-08-17 06:22 UTC
Having issue to compile the project using Xcode 15 beta 6

**Cannot specialize non-generic type 'Observable<Element>'**

![Screenshot 2023-08-17 at 09 15 31](https://github.com/RxSwiftCommunity/RxSwiftExt/assets/9766094/4522ba8a-6554-4a38-948d-8e29ff312e05)

![Screenshot 2023-08-17 at 09 15 46](https://github.com/RxSwiftCommunity/RxSwiftExt/assets/9766094/36953391-e0cb-4a07-811a-847b3aab087c)

**Comment by freak4pc** [comment] 2023-08-17 06:23
Hey, please see here:
https://github.com/ReactiveX/RxSwift/issues/2532

This is a regression from Beta 5 and we're waiting to see if they resolve it:
https://github.com/apple/swift/issues/67815

**Comment by mhaashim** [comment] 2023-08-17 12:11
<img width="1777" alt="Screenshot 2023-08-17 at 5 38 47 PM" src="https://github.com/RxSwiftCommunity/RxSwiftExt/assets/112482732/43c927be-bf9e-45f2-b512-57c9d3d77de0">

Getting the same error for me. The Xcode doesn't build the app due to this error. Please resolve this. Getting this on Xcode 15 beta 6

**Comment by rudedogdhc** [comment] 2023-08-22 20:40
I can confirm that it is not yet resolved with Xcode 15 beta 7.

**Comment by freak4pc** [comment] 2023-08-23 12:58
I've added a fix to 6.2.0

**Closed by freak4pc** 2023-08-23 12:58 UTC

**Comment by TR0NZ0D** [comment] 2023-08-23 14:03
@freak4pc Any plans on updating this new 6.2.0 version to CocoaPods? We're being blocked from doing a regression in Xcode beta 6+

**Comment by freak4pc** [comment] 2023-08-23 14:04
Yes, it's just been a nightmare uploading new things to CocoaPods but I'm working on it.

**Comment by TR0NZ0D** [comment] 2023-08-23 14:13
> Yes, it's just been a nightmare uploading new things to CocoaPods but I'm working on it.

No worries, I'll try to use the 6.2.0 version without CocoaPods meanwhile, take your time.

Thanks

**Comment by adamsousa** [comment] 2023-09-06 03:04
Seeing this issue in Xcode 15 Beta 8

**Comment by adamsousa** [comment] 2023-09-06 14:40
This issue has not been fixed because the alias file was not correct added to the project. Created a PR that corrects this by adding the file to the correct targets and the project file: https://github.com/RxSwiftCommunity/RxSwiftExt/pull/275

**Comment by Dhananjayaraop** [comment] 2023-10-30 07:42
Currently I am using Pod version  'RxSwiftExt', '6.0.1' . I am getting below errors in Xcode 15. Could you please provide updated pod version!. Find the attached screenshot.
<img width="1003" alt="Screenshot 2023-10-30 at 1 10 46 PM" src="https://github.com/RxSwiftCommunity/RxSwiftExt/assets/133747684/1e9c50c2-d006-40bd-b3e7-e1d8682ab1dc">

**Comment by ThomasReyskens** [comment] 2023-11-30 16:21
I fixed it by prefixing all Observables w/ `RxSwift`. For example -> 
<img width="557" alt="image" src="https://github.com/RxSwiftCommunity/RxSwiftExt/assets/63791073/5ae27742-703a-4bdd-8771-475c3434672c">
